export {
  projects,
  customers,
  vendors,
  vendorContacts,
  quotes,
  navigationItems,
  projectStatuses,
  navItemTypes,
  uiSlots,
  insertProjectSchema,
  insertCustomerSchema,
  insertVendorSchema,
  insertVendorContactSchema,
  insertQuoteSchema,
  insertNavigationItemSchema,
  type InsertProject,
  type InsertCustomer,
  type InsertVendor,
  type InsertVendorContact,
  type InsertQuote,
  type InsertNavigationItem,
  type Project,
  type Customer,
  type Quote,
  type Vendor,
  type VendorContact,
  type NavigationItem,
  type ProjectStatus,
  type NavItemType,
  type UiSlot,
  type CustomerWithQuote,
  type VendorWithContacts,
} from "../schema.js";
